accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'accounts'
urlpatterns = [
    # Django auth
    path('login', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
    path('profile/', views.ProfileView.as_view(), name='profile'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('public.urls')),
    path('accounts/', include('accounts.urls')),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User


class UserPersona(models.Model):
    name = models.CharField(max_length=64, unique=True)
    normalized_name = models.CharField(max_length=64, unique=True)
    description = models.TextField(max_length=200)

    def __str__(self):
        return self.name


class UserProfile(models.Model):
    # owner
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    is_ful_name_displayed = models.BooleanField(default=True)
    persona = models.ForeignKey(UserPersona, on_delete=models.SET_NULL, blank=True, null=True)

    # details
    bio = models.CharField(max_length=500, blank=True, null=True)
    website = models.URLField(max_length=200, blank=True, null=True)

news/models.py
from django.db import models
from django.contrib.auth.models import User


class Author(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    rating = models.SmallIntegerField(default=0)


class Category(models.Model):
    tatle = models.CharField(max_length=64, unique=True)


class Post(models.Model):
    NEWS = 'NW'
    ARTICLE = 'AR'
    POST_TYPES = [
        (NEWS, 'Новость'),
        (ARTICLE, 'Статья'),
    ]

    title = models.CharField(max_length=128, unique=True)
    text = models.TextField()
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    type = models.CharField(max_length=3, choices=POST_TYPES, default=ARTICLE)
    created_at = models.DateTimeField(auto_now_add=True)
    category = models.ManyToManyField(Category, through='PostCategory')
    rating = models.SmallIntegerField(default=0)


class PostCategory(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    rating = models.SmallIntegerField(default=0)

accounts/views.py
from django.views.generic.base import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin


class ProfileView(LoginRequiredMixin, TemplateView):
    template_name = 'accounts/profile.html'

news/views.py
from django.shortcuts import render
from django.http import HttpResponse


def index(request):
        return HttpResponse('Homepage')

templates/about.html
{% extends 'base.html' %}

{% block title %}About{% endblock title %}

{% block content %}
    <h1>About page template</h1>
{% endblock content %}

templates/accounts/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock title %}

{% block content %}
    <h1>Login</h1>

  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
  </form>
{% endblock content %}

templates/accounts/profile.html
{% extends 'base.html' %}

{% block title %}Prifile{% endblock title %}

{% block content %}
    <h1>{{ user.username }}'s profile</h1>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>NewsPaper - {% block title %}{% endblock title %}</title>
</head>
<body>

    {% include 'inc/navbar.html' %}

        <main>
            {% block content %}

            {% endblock content %}
        </main>
</body>
</html>

templates/contact.html
{% extends 'base.html' %}

{% block title %}Contact{% endblock title %}

{% block content %}
    <h1>Contact page template</h1>
{% endblock content %}

templates/inc/navbar.html
<nav>
    <!--  Public  -->
    {% url 'public:home' as home_url %}
    <span>{% if request.path == home_url %}Home{% else %}<a href="{{ home_url }}">Home</a>{% endif %}</span>
    {% url 'public:news' as news_url %}
    <span>{% if request.path == news_url %}News{% else %}<a href="{{ news_url }}">News</a>{% endif %}</span>
    {% url 'public:about' as about_url %}
    <span>{% if request.path == about_url %}About{% else %}<a href="{{ about_url }}">About</a>{% endif %}</span>
    {% url 'public:contact' as contact_url %}
    <span>{% if request.path == contact_url %}Contact{% else %}<a href="{{ contact_url }}">Contact</a>{% endif %}</span>
    <!--  / Public  -->

    <!--  Auth  -->
    <span style="float: right;">
        {% if user.is_authenticated %}
            {% url 'accounts:profile' as profile_url %}
        <span>Hi, {% if request.path == profile_url %}{{ user.username }}{% else %}<a href="{{ profile_url }}">{{ user.username }}!</a>{% endif %}</span>
        <span><a href="{% url 'accounts:logout' %}">Logout</a></span>
        {% else %}
        <span><a href="{% url 'accounts:login' %}">Login</a></span>
        {% endif %}
    </span>
    <!--  / Auth  -->
</nav>

templates/index.html
{% extends 'base.html' %}

{% block title %}Home{% endblock title %}

{% block content %}
    <h1>Home page template</h1>
{% endblock content %}

templates/news.html
{% extends 'base.html' %}

{% block title %}News{% endblock title %}

{% block content %}
    <h1>News page template</h1>
{% endblock content %}